CREATE TABLE IF NOT EXISTS `jos_tb_clients` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `title` varchar(16) NOT NULL,  `first_name` varchar(32) NOT NULL DEFAULT '0',  `last_name` varchar(32) NOT NULL,  `birthdate` date NOT NULL,  `street` varchar(64) NOT NULL,  `cip` varchar(5) NOT NULL,  `city` varchar(64) NOT NULL,  `country` varchar(32) NOT NULL DEFAULT 'Deutschland',  `telefone` varchar(32) NOT NULL,  `telefax` varchar(32) DEFAULT '0',  `email` varchar(255) NOT NULL,  `mobile` varchar(16) DEFAULT '0',  `published` tinyint(3) NOT NULL DEFAULT '0',  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `remark` varchar(255) DEFAULT NULL,  `question1` varchar(64) DEFAULT NULL,  `question2` varchar(64) DEFAULT NULL,  `single` tinyint(3) NOT NULL DEFAULT '0',  `double` tinyint(3) NOT NULL DEFAULT '0',  `feeder` int(11) NOT NULL DEFAULT '0',  `hotel` int(11) NOT NULL DEFAULT '0',  `total` decimal(10,2) NOT NULL DEFAULT '0.00',  `services` text NOT NULL,  `ip` varchar(15) NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `cnt_id` (`id`),  KEY `cnt_id_2` (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=50 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC ;
CREATE TABLE IF NOT EXISTS `jos_tb_clt_dat` (  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,  `dat_id` int(11) unsigned DEFAULT NULL,  `clt_id` int(11) unsigned DEFAULT NULL,  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `ip` varchar(15) DEFAULT NULL,  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=49 DEFAULT CHARSET=utf8 ;
CREATE TABLE IF NOT EXISTS `jos_tb_dat_prt` (  `prt_id` int(11) unsigned NOT NULL,  `dat_id` int(11) unsigned NOT NULL,  `markup` decimal(3,0) DEFAULT '0',  `id` int(11) NOT NULL AUTO_INCREMENT,  `ordering` int(3) unsigned NOT NULL DEFAULT '0',  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED ;
CREATE TABLE IF NOT EXISTS `jos_tb_feeder` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(16) NOT NULL,  `iata` varchar(3) DEFAULT '0',  `published` tinyint(3) NOT NULL DEFAULT '0',  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC ;
CREATE TABLE IF NOT EXISTS `jos_tb_guests` (  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,  `title` varchar(16) NOT NULL,  `first_name` varchar(32) NOT NULL,  `last_name` varchar(32) NOT NULL,  `birthdate` date NOT NULL,  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  `published` tinyint(3) NOT NULL DEFAULT '0',  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',  `id_clt` int(11) NOT NULL,  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=81 DEFAULT CHARSET=utf8 ;
CREATE TABLE IF NOT EXISTS `jos_tb_hotels` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(255) NOT NULL,  `catid` int(11) NOT NULL DEFAULT '0',  `city` varchar(32) NOT NULL,  `published` tinyint(3) NOT NULL DEFAULT '0',  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',  `rate` decimal(10,2) NOT NULL DEFAULT '0.00',  `chain` varchar(50) DEFAULT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `htl_id` (`id`),  KEY `htl_id_2` (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC ;
CREATE TABLE IF NOT EXISTS `jos_tb_journey` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `title` varchar(255) NOT NULL,  `subtitle` varchar(255) NOT NULL,  `year` int(11) NOT NULL DEFAULT '2009',  `continent` varchar(16) NOT NULL,  `region` varchar(32) NOT NULL,  `country` varchar(32) NOT NULL,  `picture` varchar(255) DEFAULT NULL,  `published` tinyint(3) NOT NULL DEFAULT '0',  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',  `catid` int(11) NOT NULL DEFAULT '0',  `select_hotel` tinyint(3) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `jrn_id` (`id`),  KEY `jrn_id_2` (`id`),  KEY `catid` (`catid`) ) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC ;
CREATE TABLE IF NOT EXISTS `jos_tb_jrn_htl` (  `jrn_id` int(11) unsigned NOT NULL,  `htl_id` int(11) unsigned NOT NULL,  `accomodation` tinyint(2) unsigned NOT NULL DEFAULT '1',  `ordering` int(3) unsigned NOT NULL,  `id` int(11) NOT NULL AUTO_INCREMENT,  `rate` decimal(10,2) NOT NULL DEFAULT '0.00',  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED ;
CREATE TABLE IF NOT EXISTS `jos_tb_jrn_srv` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `jrn_id` int(11) unsigned NOT NULL,  `srv_id` int(11) unsigned NOT NULL,  `ordering` int(3) unsigned NOT NULL DEFAULT '0',  PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED ;
CREATE TABLE IF NOT EXISTS `jos_tb_mails` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `mailbody` mediumtext NOT NULL,  `published` tinyint(3) NOT NULL DEFAULT '0',  `from` varchar(64) NOT NULL DEFAULT '''''',  `fromname` varchar(64) NOT NULL DEFAULT '''''',  `subject` varchar(49) NOT NULL DEFAULT '''''',  `cc` varchar(64) DEFAULT NULL,  `bcc` varchar(64) DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `id` (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 ;
CREATE TABLE IF NOT EXISTS `jos_tb_season` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `jrn_id` int(11) unsigned DEFAULT NULL,  `departure` date NOT NULL,  `arrival` date NOT NULL,  `rate` decimal(10,0) NOT NULL,  `available` int(2) unsigned NOT NULL,  `single_supplement` decimal(10,0) NOT NULL,  `ordering` int(3) unsigned NOT NULL,  `published` tinyint(3) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `dat_id` (`id`),  KEY `dat_id_2` (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED ;
CREATE TABLE IF NOT EXISTS `jos_tb_services` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `catid` int(11) NOT NULL DEFAULT '0',  `name` varchar(255) NOT NULL,  `srv_type` int(11) NOT NULL DEFAULT '0',  `rate` decimal(10,0) NOT NULL DEFAULT '0',  `checked` tinyint(1) unsigned NOT NULL DEFAULT '0',  `pro_rata` varchar(50) NOT NULL DEFAULT 'pro Person',  `ordering` int(3) unsigned NOT NULL,  `published` tinyint(3) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `srv_id` (`id`),  KEY `srv_id_2` (`id`),  KEY `catid` (`catid`) ) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC ;

CREATE TABLE IF NOT EXISTS `jos_categories` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `parent_id` int(11) NOT NULL DEFAULT '0',  `title` varchar(255) NOT NULL DEFAULT '',  `name` varchar(255) NOT NULL DEFAULT '',  `alias` varchar(255) NOT NULL DEFAULT '',  `image` varchar(255) NOT NULL DEFAULT '',  `section` varchar(50) NOT NULL DEFAULT '',  `image_position` varchar(30) NOT NULL DEFAULT '',  `description` text NOT NULL,  `published` tinyint(1) NOT NULL DEFAULT '0',  `checked_out` int(11) unsigned NOT NULL DEFAULT '0',  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',  `editor` varchar(50) DEFAULT NULL,  `ordering` int(11) NOT NULL DEFAULT '0',  `access` tinyint(3) unsigned NOT NULL DEFAULT '0',  `count` int(11) NOT NULL DEFAULT '0',  `params` text NOT NULL,  PRIMARY KEY (`id`),  KEY `cat_idx` (`section`,`published`,`access`),  KEY `idx_access` (`access`),  KEY `idx_checkout` (`checked_out`) ) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 ;
LOCK TABLES `jos_categories` WRITE ;
ALTER TABLE `jos_categories` DISABLE KEYS ;
INSERT INTO `jos_categories` (`parent_id`, `title`, `name`, `alias`, `image`, `section`, `image_position`, `description`, `published`, `checked_out`, `checked_out_time`, `editor`, `ordering`, `access`, `count`, `params`) 
VALUES  
(0,'Reisen','','reisen','','com_tour_details','left','',1,'0','0000-00-00 00:00:00',NULL,1,0,0,''),  
(0,'Verpflegung','','food & beverages','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,3,0,0,''),  
(0,'Service','','service','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,4,0,0,''),  
(0,'Ausfl&uuml;ge und Eintritt','','excursions','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,5,0,0,''),  
(0,'Flug','','flight','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,6,0,0,''),  
(0,'Visa','','visa','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,7,0,0,''),  
(0,'&Uuml;bernachtung','','accomodation','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,2,0,0,''),  
(0,'Transfer','','transfer','','com_service_details','left','',1,'0','0000-00-00 00:00:00',NULL,1,0,0,''),  
(0,'inclusiv','','inclusiv','','com_service_type','left','',1,'0','0000-00-00 00:00:00',NULL,0,0,0,''),  
(0,'checkbox','','Checkbox','','com_service_type','left','',1,'0','0000-00-00 00:00:00',NULL,0,0,0,''),  
(0,'radio','','Radio','','com_service_type','left','',1,'0','0000-00-00 00:00:00',NULL,0,0,0,''),  
(0,'1*','','1*','','com_hotel_details','left','',1,'0','0000-00-00 00:00:00',NULL,0,0,0,'') ;  
ALTER TABLE `jos_categories` ENABLE KEYS ;
UNLOCK TABLES ;